FORMAT: 1A

# Horizon

The horizon description goes here

## Account [/accounts/{address}]

Represents the current state of an account as of the latest closed
ledger imported by horizon.

+ Model (application/hal+json)

        {
          "_links": {
            "self": {
              "href": "/accounts/gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs"
            },
            "transactions": {
              "href": "/accounts/gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs/transactions{?order}{?limit}{?after}{?before}"
            }
          },
          "id": "gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs",
          "address": "gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs",
          "sequence": 3,
          "balances": [{
            "asset": {
              "type": "native"
            },
            "balance": 100000000
          },{
            "asset": {
              "type": "credit_alphanum_4",
              "code": "USD",
              "issuers": "gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7"
            },
            "balance": 100000000
          }]
        }

### View account details [GET]

+ Parameters

  + address (required, string, `gjgPNE2GpySt5iYZaFFo1svCJ4gbHwXxUy8DDqeYTDK6UzsPTs`) ... Address of an account

+ Response 200

    [Account][]

## Transaction [/transactions/{hash}]

Represents a single transaction that has been submitted and validated by the stellar network

+ Model (application/hal+json)

        {
          "_links": {
            "self": {
              "href": "/transactions/4774bce2ddf7cf9332d5f97ab7f7bff115291d5598c7eec827f43ca58bd4fa06"
            },
            "account": {
              "href": "/accounts/gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7"
            }
          },
          "hash": "4774bce2ddf7cf9332d5f97ab7f7bff115291d5598c7eec827f43ca58bd4fa06",
          "ledger": 7,
          "application_order": [
            7,
            2
          ],
          "account": "gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7",
          "account_sequence": 2,
          "fee_paid": 10,
          "operation_count": 1
        }


### View transaction's details [GET]

  + Parameters

    + hash (required, string, `0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54`) ... The hex-encoded hash of a transaction

  + Response 200

      [Transaction][]


## Transaction Collection [/transactions{?order}{?limit}{?after}]

+ Model (application/hal+json)

        {
          "_links": {
            "next": {
              "href": "/transactions?after=373a31&limit=1&order=asc"
            }
          },
          "_embedded": {
            "records": [
              {
                "_links": {
                  "self": {
                    "href": "/transactions/0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54"
                  },
                  "account": {
                    "href": "/accounts/gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7"
                  }
                },
                "hash": "0ab231385734ad4092cc0651f3acd2a6e3eead24282f2725a79d019d4b791d54",
                "ledger": 7,
                "application_order": [
                  7,
                  1
                ],
                "account": "gM4gu1GLe3vm8LKFfRJcmTt1eaEuQEbo61a8BVkGcou78m21K7",
                "account_sequence": 1,
                "fee_paid": 10,
                "operation_count": 1
              }
            ]
          }
        }

### View a page of transaction history [GET]

  + Parameters
    + after (optional, string, `373a31`) ... A paging token
    + limit (optional, number, `10`) ... The maximum number of transactions to return in the response
    + order (string)

        The order to traverse the transaction collection

        + Values
            + `asc`
            + `desc`

  + Response 200

    [Transaction Collection][]


### Submitting a transaction [POST]

  + Parameters
    + tx (required, string, `ffffff`) ... The hex-encoded xdr form of the transaction to be submitted

  + Request (application/x-www-form-urlencoded)

        tx=fffff

  + Response 200 (application/hal+json)

        {
          "hash": "67071d24b1859ea5f2f5315961ab84accebea8f6ec907aed728d172ba7058acf",
          "result": "already_finished",
          "submission_result": null,
          "_links": {
            "transaction": {
              "href": "/transactions/67071d24b1859ea5f2f5315961ab84accebea8f6ec907aed728d172ba7058acf"
            }
          }
        }

  + Response 201 (application/hal+json)
        {
          "hash": "64672a11e41f1e0530e49dcf6aedd3cf00ba4314ed240f18dfaad6730d1a9afc",
          "result": "received",
          "submission_result": "000000000000000a0000000000000001000000000000000000000000"
        }

## Friendbot (Lumen Faucet) [/friendbot]

When configured with a secret key, horizon can fund accounts to help you test your applications.  Friendbot gives them out.

### Fund Account [POST]

  + Request (application/x-www-form-urlencoded)

        addr=gsaKhsFcxHmo3PMeCHrvHJAcqJrLhy11WexgUiwRMmz7cpKV55w

  + Response 200 (application/hal+json)
        {
          "hash": "64672a11e41f1e0530e49dcf6aedd3cf00ba4314ed240f18dfaad6730d1a9afc",
          "result": "received",
          "submission_result": "000000000000000a0000000000000001000000000000000000000000"
        }

  + Response 404 (application/hal+json)
        {
          "type": "not_found",
          "status": 404,
          "title": "Resource Missing",
          "instance": "request://08a9edea-a20c-4b93-95b5-fdfff985b4c9"
        }
